// <auto-generated>
//     This code was generated manually to provide strongly typed access to StationsNRoutes resources.
// </auto-generated>

#nullable disable

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace NobUS.Resources.Definitions;

[GeneratedCode("Manual", "1.0.0.0")]
[DebuggerNonUserCode]
[CompilerGenerated]
public static class StationsNRoutes
{
    private static ResourceManager resourceMan;
    private static CultureInfo resourceCulture;

    internal static ResourceManager ResourceManager =>
        resourceMan
        ??=
            new ResourceManager(
                "NobUS.Resources.Definitions.StationsNRoutes",
                typeof(StationsNRoutes).Assembly
            );

    internal static CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string NUS_Mapping => ResourceManager.GetString("NUS-Mapping", resourceCulture)!;

    public static string NUS_Routes => ResourceManager.GetString("NUS-Routes", resourceCulture)!;

    public static string NUS_Stations => ResourceManager.GetString("NUS-Stations", resourceCulture)!;

    public static string Public_Stations => ResourceManager.GetString("Public-Stations", resourceCulture)!;
}
