name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10 RC2 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.100-rc.2.25502.107

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj', '**/*.props', '**/*.targets', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install MAUI workloads (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: dotnet workload install maui-android --skip-manifest-update --source https://api.nuget.org/v3/index.json

      - name: Install MAUI workloads (Windows/macOS)
        if: matrix.os != 'ubuntu-latest'
        run: dotnet workload install maui maui-android --skip-manifest-update --source https://api.nuget.org/v3/index.json

      - name: Restore dependencies
        run: dotnet restore NobUS.sln

      - name: Build solution
        run: dotnet build NobUS.sln -c Release --no-restore

      - name: Run tests (if present)
        shell: bash
        run: |
          set -euo pipefail
          if find . -name '*Test*.csproj' | grep -q .; then
            dotnet test NobUS.sln -c Release --no-build
          else
            echo "No test projects found. Skipping dotnet test."
          fi
